networks: { cloud-net: { name: cloud-net } }
services:
  web-frontend-server:
    build: ./web-frontend-server
    image: tranthuyendocker/myminicloud-web:dev # đã build tên mới
    # image: thuyenkietkiet/web:dev
    container_name: web-frontend-server
    networks: [cloud-net]
    ports: [ "8080:80" ]
    restart: unless-stopped
    volumes:
      - ./web-frontend-server/conf.default:/etc/nginx/conf.d/default.conf:ro
  web-frontend-server-2:
    build:
      context: ./web-frontend-server
      dockerfile: Dockerfile.web2
    image: tranthuyendocker/myminicloud-web2:dev
    container_name: web-frontend-server-2
    networks: [cloud-net]
    ports: [ "8082:80" ]
    restart: unless-stopped
    volumes:
      - ./web-frontend-server/conf.default:/etc/nginx/conf.d/default.conf:ro

  application-backend-server:
    build: ./application-backend-server
    image: tranthuyendocker/myminicloud-app:dev
    container_name: application-backend-server
    networks: [cloud-net]
    ports: [ "8085:8081" ]
    restart: unless-stopped
    environment:
      OIDC_ISSUER: "http://authentication-identity-server:8080/realms/master"
      OIDC_AUDIENCE: "myapp"
    volumes:
      - ./application-backend-server/students.json:/app/students.json:ro
      - ./application-backend-server/app.py:/app/app.py:ro
  relational-database-server:
    image: mariadb:11
    container_name: relational-database-server
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_ROOT_HOST: "%"
      MARIADB_DATABASE: minicloud
    volumes:
    - ./relational-database-server/init:/docker-entrypoint-initdb.d:ro
    # ports: [ "3306:3306" ]
    ports: [ "3320:3306" ]
    restart: unless-stopped
    networks: [cloud-net]
    
  authentication-identity-server:
    image: quay.io/keycloak/keycloak:latest
    container_name: authentication-identity-server
    command: ["start-dev"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: "localhost"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports: [ "8081:8080" ]
    restart: unless-stopped
    networks: [cloud-net]

  object-storage-server:
    image: minio/minio
    container_name: object-storage-server
    command: ["server","/data","--console-address",":9001"]
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./object-storage-server/data:/data
    ports: [ "9000:9000", "9001:9001" ]
    restart: unless-stopped
    networks: [cloud-net]

  internal-dns-server:
    image: internetsystemsconsortium/bind9:9.18
    container_name: internal-dns-server

    # ÉP named log ra stdout để docker thấy lỗi
    command: ["-u", "bind", "-f", "-g", "-c", "/etc/bind/named.conf"]

    ports:
      - "1053:53/udp"
      - "1053:53/tcp" 

    # CHO PHÉP GHI (bỏ :ro) để tránh lỗi permission vớ vẩn
    volumes:
      - ./internal-dns-server:/etc/bind

    # Tạm bỏ tmpfs cho đơn giản (có cũng được, nhưng mình bỏ để giảm biến số)
    # tmpfs:
    #   - /run/named
    #   - /var/cache/bind

    # Tạm thời KHÔNG restart, để nó crash một lần rồi dừng, mình xem lỗi
    # restart: "no"
    restart: unless-stopped
    networks: [cloud-net]

  # internal-dns-server:
  #   image: internetsystemsconsortium/bind9:9.18
  #   container_name: internal-dns-server
  #   ports:  
  #     # - "1153:53/udp"
  #     # - "1153:53/tcp"
  #     - "1053:53/udp"
  #     - "1053:53/tcp"
  #   volumes:
  #     - ./internal-dns-server:/etc/bind:ro
  #     # - ./internal-dns-server/named.conf:/etc/bind/named.conf:ro
  #     # - ./internal-dns-server/named.conf.options:/etc/bind/named.conf.options:ro
  #     # - ./internal-dns-server/named.conf.local:/etc/bind/named.conf.local:ro
  #     # - ./internal-dns-server/db.cloud.local:/etc/bind/db.cloud.local:ro
  #   tmpfs:
  #     - /run/named
  #     - /var/cache/bind
  #   restart: unless-stopped
  #   networks: [cloud-net]

  monitoring-node-exporter-server:
    image: prom/node-exporter:latest
    container_name: monitoring-node-exporter-server
    ports: [ "9100:9100" ]
    restart: unless-stopped
    networks: [cloud-net]

  monitoring-prometheus-server:
    image: prom/prometheus:latest
    container_name: monitoring-prometheus-server
    ports: [ "9090:9090" ]
    restart: unless-stopped
    volumes:
    - ./monitoring-prometheus-server/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks: [cloud-net]

  monitoring-grafana-dashboard-server:
    image: grafana/grafana:latest
    container_name: monitoring-grafana-dashboard-server
    ports: [ "3000:3000" ]
    restart: unless-stopped
    networks: [cloud-net]

  api-gateway-proxy-server:
    image: nginx:stable
    container_name: api-gateway-proxy-server
    depends_on:
    - web-frontend-server
    - application-backend-server
    - authentication-identity-server
    ports: [ "80:80" ]
    volumes:
    - ./api-gateway-proxy-server/nginx.conf:/etc/nginx/nginx.conf:ro
    networks: [cloud-net]
    restart: unless-stopped